# Generated by Django 5.1.4 on 2024-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_values', models.TextField()),
                ('y_values', models.TextField()),
                ('error', models.FloatField()),
            ],
        ),
    ]
